# ---------------------------------------------------------------------------
# Documentation for the data shipped with the package. The data themselves are
# built by data-raw/make-sim-gist.R; this file only describes them.
# ASCII-only, like the rest of the package.
# ---------------------------------------------------------------------------

#' A simulated GIST cohort
#'
#' @description
#' A synthetic cohort of 1200 subjects, used by the examples, the tests and
#' the vignette so that every function in the package can be run end to end
#' without access to registry data.
#'
#' The outcome is supplied in the raw form a registry export arrives in --
#' a follow-up time, a vital-status string and a cause-of-death string -- and
#' not as ready-made event indicators. Call [prep_surv()] first to obtain
#' `event_os` and `event_cr`; the other six functions take it from there.
#'
#' @section What this is not:
#' `sim_gist` is **not** a sample, a subset, a perturbation or a summary of
#' SEER data, and it is not fitted to any real cohort. Every parameter is a
#' literal written into `data-raw/make-sim-gist.R`, which opens no file. The
#' marginal distributions and the two cause-specific hazards were chosen to
#' exercise the branches of the seven functions -- both competing causes
#' present in every stratum, follow-up long enough that `tau = 60` is
#' admissible, a covariate whose missingness depends on age, an unknown cause
#' of death -- and not to resemble any population. No epidemiological claim
#' can be read off it.
#'
#' What the dataset does borrow from the study the package was distilled from
#' is its *structure*: the variable names, the factor levels and the reference
#' levels. That is deliberate, so that a user can substitute their own extract
#' for `sim_gist` and have the same calls still fit.
#'
#' @format A data frame with 1200 rows and 14 columns:
#' \describe{
#'   \item{id}{Row identifier, 1 to 1200. Not a patient identifier.}
#'   \item{site}{Primary site, a factor with levels `"Stomach"` (reference),
#'     `"Small intestine"`, `"Colorectal"`.}
#'   \item{age}{Age at diagnosis in whole years, 20 to 90.}
#'   \item{age_grp}{Age group, a factor with levels `"<50"` (reference),
#'     `"50-64"`, `"65-74"`, `"75+"`.}
#'   \item{sex}{A factor with levels `"Male"` (reference), `"Female"`.}
#'   \item{race}{A factor with levels `"NH White"` (reference), `"NH Black"`,
#'     `"NH API"`, `"Hispanic"`, `"Other/Unknown"`.}
#'   \item{size_mm}{Largest tumour dimension in millimetres, 1 to 400.
#'     Missing for 150 subjects, more often in the older groups.}
#'   \item{size_grp}{Size band, a factor with levels `"<=20"` (reference),
#'     `"21-50"`, `"51-100"`, `">100"`. Missing wherever `size_mm` is.}
#'   \item{stage}{A factor with levels `"Localized"` (reference),
#'     `"Regional"`, `"Distant"`, `"Unknown"`.}
#'   \item{surgery}{Surgery of the primary site, a factor with levels `"No"`
#'     (reference) and `"Yes"`. Missing for 25 subjects.}
#'   \item{dx_year}{Year of diagnosis, 2000 to 2019. Determines how much
#'     potential follow-up a subject has, because everyone is censored at the
#'     same notional cutoff.}
#'   \item{time_mo}{Follow-up in whole months, 0 to 299.}
#'   \item{vital_status}{`"Alive"` or `"Dead"`. 564 subjects died.}
#'   \item{cause_of_death}{Cause of death in the registry's own coding, with
#'     three values: `"Dead (attributable to this cancer dx)"` (332 subjects),
#'     `"Dead (missing/unknown COD)"` (6 subjects), and
#'     `"Alive or dead of other cause"` -- which, as in the registry, covers
#'     both the living and the 226 who died of something else, and so cannot
#'     be read without `vital_status`. Resolving the two columns against each
#'     other is what [prep_surv()] is for.}
#' }
#'
#' @section Why the cause column has to be coded openly:
#' `"Alive or dead of other cause"` is carried by living subjects as well as
#' by those who died of something else. It therefore cannot be passed as
#' `cause_other_value`: [prep_surv()] treats a declared cause of death on a
#' living subject as a contradiction and stops, which is the behaviour you
#' want for every other value. Leave `cause_other_value` at its default
#' `NULL` instead. An undeclared value on a dead subject then becomes
#' `event_cr = 2`, and the same value on a living subject is simply ignored,
#' because vital status has already settled the case.
#'
#' The cost of open coding is that a value nobody anticipated -- a new
#' registry code, a typo -- also becomes a death from other causes rather than
#' an error. Check `attr(d, "os_cr_table")` and the counts in
#' `attr(d, "prep_surv")` against your own extract before going further.
#'
#' @source
#' Generated by `data-raw/make-sim-gist.R` with `set.seed(20260901)`. Re-run
#' that script to rebuild the dataset; the same seed gives the same rows.
#'
#' @examples
#' str(sim_gist)
#'
#' ## the raw cause column cannot be read on its own
#' table(sim_gist$vital_status, sim_gist$cause_of_death)
#'
#' ## prep_surv() resolves it into event_os / event_cr.
#' ## cause_other_value is left NULL on purpose: see the section above.
#' d <- prep_surv(
#'   sim_gist,
#'   time                = "time_mo",
#'   status              = "vital_status",
#'   cause               = "cause_of_death",
#'   cause_gist_value    = "Dead (attributable to this cancer dx)",
#'   cause_unknown_value = "Dead (missing/unknown COD)",
#'   cause_unknown_to    = 2L
#' )
#' attr(d, "os_cr_table")
#' attr(d, "prep_surv")$counts
"sim_gist"
